specVersion: 0.2.0
name: subql-ternoa
version: 1.0.0
description: Ternoa data indexer
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x3d9fa286092d3636b48cc2d2effff789b1a6b5cf15c54ca33a86fa7996d7d553' #dev
  endpoint: wss://dev.chaos.ternoa.com
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
