specVersion: 0.2.0
name: subql_ternoa
version: 1.0.0
description: Ternoa data indexer
repository: ""
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xb830bd7275da92f5064e9fead7605a63d2a8c6841267b96f57122867ac9a3abc"
  endpoint: wss://dev-1.ternoa.network/
  # dictionary: https://dictionary-alphanet.ternoa.dev/
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridge
            method: DepositMade

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTBurned
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTTransferred
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTDelegated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTRoyaltySet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionBurned
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionClosed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionLimited
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTAddedToCollection
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractCanceled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractStarted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractRevoked
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractOfferCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractOfferRetracted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractSubscriptionTermsChanged
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractSubscriptionTermsAccepted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractEnded
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractSubscriptionPeriodStarted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: rent
            method: ContractExpired
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceOwnerSet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceKindSet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceConfigSet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceMintFeeSet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: NFTListed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: NFTUnlisted
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: NFTSold
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: associatedAccounts
            method: UserAccountAdded
